### ISSUE TITLE
Enroll select projects with tea.xyz

### ISSUE THREAD

**Issue by jaraco** [coherent-oss/granary#5]
I've been approach by the [tea](https://tea.xyz) project to consider enrolling select projects (configparser, inflect, keyring) with tea. I've signed an agreement to do just that and this issue tracks the milestones and steps.

## Milestone 1

- [x] Sign up for the tea Protocol using one of the native sign up methods: email, google, twitter, discord.
- [x] Link the primary GitHub associated with your project(s) during or after sign-up using the tools provided by the tea Protocol incentivized testnet.
- [x] Register your project(s) with the tea Protocol using the tools provided by the tea Protocol incentivized testnet. You must register the project(s) associated with this contract.
- [x] Stake your registered project(s) from your project’s/projects’ treasury using the tools provided by the tea Protocol incentivized testnet. On-chain data will be utilised to confirm the completion of this milestone task.
- [x] Stake your registered project(s) from your own tea account using the tools provided by the tea Protocol incentivized
testnet. On-chain data will be utilised to confirm the completion of this milestone task.

## Milestone 2

- [ ] Invite OSS devs to join the tea Protocol incentivized testnet via two channels: direct marketing (email), a blog post, a public channel/forum post or social media. In order to complete this deliverable the project(s) will email a referral link to OSS devs AND post on twitter (X) inviting OSS devs and projects to join ITN.
- [ ] Utilise the tea Protocol in order to increase your teaRank. Your teaRank must go up based on your activity in order to make this milestone task completed.
- [ ] Create a proposal to the teaDAO based on your experience with the tea Protocol incentivized testnet. The proposal must be robust and relevant.
- [ ] Participate in a teaDAO by voting on a proposal using your own tea account. You can vote on any active proposal. Voting on your own proposal will not count towards this milestone task.
- [ ] Participate in a teaDAO by voting on a proposal as the project(s) associated with this contract. You can vote on any active proposal. Voting on your own proposal will not count towards this milestone task.

## Milestone 3

- [x] Post a 2-5 posts thread on you AND your project’s/projects’ twitter account(s) (if applicable) about your experience with the tea Protocol and the tea Protocol incentivized testnet. Posts must link to the tea website (https://tea.xyz) to complete the milestone task.
- [x] Verify the email address you signed up with when you joined the tea Protocol incentivized testnet using the tools provided
by the tea Protocol incentivized testnet.
- [x] Claim teaRank rewards earned from your project(s) and stake them back into your project(s) using the tools provided by the tea Protocol incentivized testnet. You must stake at least the minimum amount required by the tea Protocol to complete this milestone task.
- [x] Claim your project’s/projects’ staking rewards in the tea Protocol using the tools provided by the tea Protocol incentivized testnet.
- [ ] The individual who registered the project(s) or the project itself will have an AMA with Max Howell, the founder of tea. The AMA will be conducted on the tea twitter account at an agreed upon time by both parties. The AMA must be completed and shared on your twitter account(s) in order to complete this milestone task.

**Comment by jaraco** [comment]
A couple of weeks ago, I attempted to complete 1.3 (stake the registered projects from the projects' treasury). Today, I can confirm that inflect did get staked:

![image](https://github.com/coherent-oss/granary/assets/308610/89c356e3-9f50-4db0-a4cf-543b6ebd1ad1)

I'm pretty sure I'd tried to do the same with configparser, but it was still showing the initial balance of 10,000, so I re-processed the staking and it now shows half-staked (deducted from the treasury but not yet showing in the bug bounty):

![image](https://github.com/coherent-oss/granary/assets/308610/735dbd91-27a5-482f-a208-652e1ca13cf1)


I've also succeeded in staking keyring, but not the correct one. There are two keyrings on my account and I staked the non-PyPI one:

![image](https://github.com/coherent-oss/granary/assets/308610/b3fb665a-832a-4065-a695-c7d74a6a0d81)

Today I also requested to stake keyring (PyPI) and it's in the same state as configparser:

![image](https://github.com/coherent-oss/granary/assets/308610/1c9f33b4-5aee-4bed-8407-a98995b4c3b7)

Hopefully keyring and configparser show the staking in the bug bounty pool soon.

**Comment by sanchitram1** [comment]
configparser and keyring have successfully staked: 
- [configparser](https://sepolia.basescan.org/address/0xe8ec64ee5859bfdb3930815b24bed621b8f6313d#tokentxns)
- [keyring](https://sepolia.basescan.org/address/0x78a41c51b227ec5c9673e0a0c6c69392465807a5#tokentxns)

you can always copy the address of the project (thing below the name) and search on sepolia.basescan to confirm a txn wen through.  are they still not showing you a 0 value in the BBP?

**Comment by jaraco** [comment]
Yes! Both now show 2,500 in the BBP. Thanks!

**Comment by jaraco** [comment]
I've staked the three projects from my own test account as well:

![image](https://github.com/coherent-oss/roadmap/assets/308610/401f5e87-5485-491a-981b-98d236b87b42)

**Comment by jaraco** [comment]
Today I had the AMA with Max and will add that to my twitter account once I have the link.

**Comment by jaraco** [comment]
I've posted [this thread](https://twitter.com/jaraco/status/1795160147926413676) on Twitter for milestone 3.1 (including a call to action for fellow maintainers for half of 2.1).
